/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('../components/AppFooter.vue')['default']
    AppHeader: typeof import('../components/AppHeader.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    OrderBook: typeof import('../pages/OrderBook.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('../pages/Settings.vue')['default']
  }
}
